site_name: Sukhpreet's Project Diary
nav:
  - Home: index.md
  - Projects:
      - Project 1: projects/project1.md
      - Project 2: projects/project2.md
  - About: about.md
theme:
  name: windmill
plugins:
  - search
  
